name: VSCode Release
on:
  push:
    branches: [release]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # needs: test
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm -v
      - run: node -v
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpx zardoy-release vscode-extension
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
          # optional
          EXTENSION_ICON: ${{ secrets.EXTENSION_ICON }}
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: pnpm build-plugin:npm
      - run: node typescript/npm/beforePublish.mjs
      - run: pnpm publish --access public --no-git-checks
        working-directory: typescript
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
